<?php

namespace Louvre\TicketBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function ticketsSoldByDay($date)
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->select('COUNT(b.totalNbTickets)')
            ->where('b.ticketDate = :date')
            ->andWhere('b.paid = true')
            ->setParameter('date', $date);
        
        return $qb
            ->getQuery()
            ->getResult();
    }
}
