services:
#    louvre_ticket.example:
#        class: Louvre\TicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    louvre_ticket.ticketprice:
        class: Louvre\TicketBundle\Services\TicketsPrices
        arguments:
            - "@doctrine.orm.entity_manager"
            
    louvre_ticket.bookingcode:
        class: Louvre\TicketBundle\Services\BookingCode
        
    louvre_ticket.sendingmail:
        class: Louvre\TicketBundle\Services\SendingMail
        arguments:
            - "@mailer"
            - "@templating"